export const projectsData = [
  {
    id: 1,
    name: "Sharks",
    image: [
      "/images/portfolioImages/sharks/1.png",
      "/images/portfolioImages/sharks/2.png",
      "/images/portfolioImages/sharks/3.png",
      "/images/portfolioImages/sharks/4.png",
      "/images/portfolioImages/sharks/5.png",
    ],
    description:
      "Professional landing page for Sharks, an e-commerce development agency. Built with Next.js and TypeScript, featuring bilingual support (English/Arabic), responsive design and smooth animationsfor enhanced user experience.",
    techs: ["nextjs", "typescript", "tailwindcss", "framer-motion"],
    isBest: true,
    mainTech: "nextjs",
    category: "web application",
    link: "https://sharks-test.vercel.app",
  },
  {
    id: 2,
    name: "Syria Mart",
    image: [
      "/images/portfolioImages/syriaMart/1.jpg",
      "/images/portfolioImages/syriaMart/2.png",
      "/images/portfolioImages/syriaMart/3.png",
      "/images/portfolioImages/syriaMart/4.png",
      "/images/portfolioImages/syriaMart/5.png",
      "/images/portfolioImages/syriaMart/6.png",
      "/images/portfolioImages/syriaMart/7.png",
    ],
    description:
      "Syria Mart is a modern e-commerce platform built with Next.js, offering a seamless shopping experience with internationalization support and responsive design for the Syrian market.",
    techs: ["nextjs", "typescript", "tailwindcss", "shadcn-UI"],
    isBest: true,
    mainTech: "nextjs",
    category: "web application",
    link: "https://syria-mart.com",
  },
  {
    id: 3,
    name: "Meme Generator",
    image: [
      "/images/portfolioImages/memeGenerator/1.png",
      "/images/portfolioImages/memeGenerator/2.png",
      "/images/portfolioImages/memeGenerator/3.png",
    ],
    description:
      "A dynamic React application that generates memes by leveraging data from an external API, providing users with an interactive and entertaining experience.",
    techs: ["react", "html2canvas"],
    github: "https://github.com/Abdulmajeed-Tawfiq/meme-generator",
    link: "https://abdulmajeed-tawfiq.github.io/meme-generator",
    isBest: false,
    mainTech: "React",
    category: "web application",
  },
  {
    id: 4,
    name: "E-commerce",
    image: [
      "/images/portfolioImages/ecommerce/1.png",
      "/images/portfolioImages/ecommerce/2.png",
      "/images/portfolioImages/ecommerce/3.png",
      "/images/portfolioImages/ecommerce/4.png",
    ],
    description:
      "full-stack E-commerce application that leverages the power of React for a dynamic and responsive frontend, Redux for state management and API from fakestoreapi",
    techs: ["react", "redux", "react-router-dom"],
    github: "https://github.com/Abdulmajeed-Tawfiq/ecommerce",
    link: "https://ecommercereact2.vercel.app",
    isBest: false,
    mainTech: "React",
    category: "e-commerce",
  },
  {
    id: 5,
    name: "Dashboard",
    image: [
      "/images/portfolioImages/dashboard/1.png",
      "/images/portfolioImages/dashboard/2.png",
      "/images/portfolioImages/dashboard/3.png",
      "/images/portfolioImages/dashboard/4.png",
    ],
    description:
      "Next-Dashboard is a comprehensive web application built using Next.js, React, and TypeScript. It provides a platform for managing products, transactions, and users, with a focus on simplicity and efficiency.",
    techs: ["nextjs", "tailwindcss", "typescript"],
    github: "https://github.com/Abdulmajeed-Tawfiq/dashboard",
    link: "https://abdulmajeed-dashboard.vercel.app",
    isBest: false,
    mainTech: "nextjs",
    category: "web application",
  },
  {
    id: 6,
    name: "Kasper",
    image: [
      "/images/portfolioImages/kasper/1.png",
      "/images/portfolioImages/kasper/2.png",
      "/images/portfolioImages/kasper/3.png",
      "/images/portfolioImages/kasper/4.png",
    ],
    description:
      "Kasper is a comprehensive website template designed for developers seeking a modern, visually appealing starting point for their projects. Built with HTML and CSS.",
    techs: ["html", "css"],
    github: "https://github.com/Abdulmajeed-Tawfiq/Kasper-Template",
    link: "https://abdulmajeed-tawfiq.github.io/Kasper-Template",
    isBest: false,
    mainTech: "CSS",
    category: "template",
  },
  {
    id: 7,
    name: "Leon",
    image: [
      "/images/portfolioImages/leon/1.png",
      "/images/portfolioImages/leon/2.png",
      "/images/portfolioImages/leon/3.png",
      "/images/portfolioImages/leon/4.png",
    ],
    description:
      "Leon is a comprehensive website template designed for developers seeking a modern, visually appealing starting point for their projects. Built with HTML and CSS.",
    techs: ["html", "css"],
    github: "https://github.com/Abdulmajeed-Tawfiq/Leon-Template",
    link: "https://abdulmajeed-tawfiq.github.io/Leon-Template",
    isBest: false,
    mainTech: "CSS",
    category: "template",
  },
];
