
export const projectsData = [
  {
    id: 1,
    name: "Dashborad",
    image: "../../public/images/portfolioImages/dashboard/1.png",
    description: "Next-Dashboard is a comprehensive web application built using Next.js, React, and TypeScript. It provides a platform for managing products, transactions, and users, with a focus on simplicity and efficiency.",
    techs: ['nextjs', 'tailwindcss', 'typescript'],
    github: 'https://github.com/Abdulmajeed-Tawfiq/dashboard',
    link: 'https://abdulmajeed-dashboard.vercel.app',
  },
  {
    id: 2,
    name: "E-commerce",
    image: "../../public/images/portfolioImages/ecommerce/1.png",
    description: "full-stack E-commerce application that leverages the power of React for a dynamic and responsive frontend, Redux for state management and API from fakestoreapi",
    techs: ['react', 'redux', 'react-router-dom'],
    github: 'https://github.com/Abdulmajeed-Tawfiq/ecommerce',
    link: 'https://ecommercereact2.vercel.app',
  },
  {
    id: 3,
    name: "Kasper",
    image: "../../public/images/portfolioImages/kasper/1.png",
    description: "Kasper is a comprehensive website template designed for developers seeking a modern, visually appealing starting point for their projects. Built with HTML and CSS.",
    techs: ['html', 'css'],
    github: 'https://github.com/Abdulmajeed-Tawfiq/Kasper-Template',
    link: 'https://abdulmajeed-tawfiq.github.io/Kasper-Template',
  },
  {
    id: 4,
    name: "Leon",
    image: "../../public/images/portfolioImages/leon/1.png",
    description: "Leon is a comprehensive website template designed for developers seeking a modern, visually appealing starting point for their projects. Built with HTML and CSS.",
    techs: ['html', 'css'],
    github: 'https://github.com/Abdulmajeed-Tawfiq/Leon-Template',
    link: 'https://abdulmajeed-tawfiq.github.io/Leon-Template',
  },
  {
    id: 5,
    name: "meme-generator",
    image: "../../public/images/portfolioImages/memeGenerator/1.png",
    description: "A dynamic React application that generates memes by leveraging data from an external API, providing users with an interactive and entertaining experience.",
    techs: ['react', 'html2canvas'],
    github: 'https://github.com/Abdulmajeed-Tawfiq/meme-generator',
    link: 'https://abdulmajeed-tawfiq.github.io/meme-generator',
  },
];
